RIOT-OS/riotdocker

- Dockerfile
Added cppcheck and Doxygen to use this image as a base system for CI testing. The static tests group requires that cppcheck and doxygen can be run in order to look for style errors.
> latest: Add cppcheck and doxygen for static tests

- Dockerfile
- native/Dockerfile
Each `RUN` command in the Dockerfile adds a file system layer to the container. Joining commands on a single line using `&&` results in less layers and less overhead.
This joins the update and dist-upgrade commands on a single line, there is really no use for them as separate layers.
> Less layers by joining commands

- Dockerfile
The new drone build script uses GNU parallel to speed up the build process (See https://github.com/RIOT-OS/RIOT/pull/3038)
> added GNU parallel

- Dockerfile
Since we merged RIOT-OS/RIOT#3229 ```hexdump``` is needed for building the unit tests.
> add bsdutils (hexdump) to dockerfile

- Dockerfile
- arm/Dockerfile
- native/Dockerfile
The llvm package does not contain the main clang binary on Debian.
The original intention of the llvm package in the Dockerfiles was to provide clang inside the containers.
> arm+native: Add clang

- Dockerfile
This PR sets up a global user and email address for git.
Rationale: When using docker to build a test that requires a package with patches, then
the patching returns the following error:
```
fatal: unable to look up current user in the passwd file: no such user
You need to set your committer info first
```
Can be invoked by issueing
```
BUILD_IN_DOCKER=1 BOARD=native make distclean clean all
```
in the `$(RIOTBASE)/tests/coap` folder.
> docker: add global system-wide git user and email address

- Dockerfile
- arm/Dockerfile
- avr/Dockerfile
- msp430/Dockerfile
- native/Dockerfile
- native/run.sh
- run.sh
- x86/Dockerfile
Sometimes when pressing ctrl-c to abort a build the container doesn't exit and one make process usually starts to use 100% cpu in an infinite loop. This seem to be caused by not handling signals properly. This script adds a signal handler for SIGTERM (kill) and SIGINT (ctrl-c) to ask the subprocesses to terminate before exiting.
Tested on my own machine, both ctrl-c and kill, both directed at the top level sh process and the make and the gcc processes. I have not had a single case of stuck processes so far.
Bonus commit: Changed my last name where I could find it.
> Add signal wrapper

- Dockerfile
- run.sh
Updated Dockerfile to use Ubuntu 15.10 "Wily" as base image instead of Debian Jessie.
Also switched to gcc-arm-embedded toolchain (officially supported by ARM) which fixes the issue with `PRIu32` and Clang reported in #9 
Based on #14
> Use Ubuntu 15.10 Wily as base, switch to gcc-arm-embedded toolchain

- Dockerfile
- run.sh
based on #15 
This merges all apt commands into a single RUN line to avoid creating extra layers and removes the apt repository cache after installation finishes.
The image size is reduced by ca 30 MB. It's not much reduction for an image of 1.5 GB, but less layers can also slightly reduce the runtime overhead, which can be helpful when using lots and lots of ephemeral containers like for a CI build bot (RIOT-CI).
> Clean up apt after installation

- Dockerfile
static-tests are probably soon running "make term" through gdb in order to see backtraces.
> dockerfile: add native gdb

- Dockerfile
This PR changes the wily (15.10) base image to xenial (16.04) and adapts the Cortex-M PPA accordingly.
> Move to Ubuntu 16.04 base image

- Dockerfile
- create_user.c
- run.sh
This PR makes sure that the uid executing a command within the container has a proper passwd entry.
This solves some trouble with stuff requiring a user entry:
```
I have no name!@984e0102d179:/data/riotbuild$ ssh booze
No user exists for uid 1000
I have no name!@984e0102d179:/data/riotbuild$
```
vs.
```
riotbuild@bb9627754a88:~$ ssh booze
The authenticity of host 'booze (192.168.1.150)' can't be established.
ECDSA key fingerprint is SHA256:JgfpYCuH13M74r4kJnRt+yegIdQq5F5BW68FADcYf1I.
Are you sure you want to continue connecting (yes/no)?
```
> add tool to create a passwd entry for user running the container

- Dockerfile
Currently, Murdock is copying a [ccache](https://github.com/RIOT-OS/murdock-scripts) binary into the docker image at runtime.
@kaspar030 was there any reasoning to use a local binary instead of using ccache from upstream?
> dockerfile: add ccache

- Dockerfile
This PR adds the mips toolchain to our Docker image.
Test using https://github.com/RIOT-OS/RIOT/pull/6060, build board "mips-malta".
> add mips toolchain

- Dockerfile
Here's a small collection of fixes for our Docker image:
1. cut off the cleaning step of the package installation phase
This is more a developing aid. Every time something needs to be added, a full re-installation of all packages is needed. With this PR, it becomes possible to just install packages after the main bunch, making use of docker's caching, saving a lot of time.
2. /tmp/create_user.c is leftover but unneeded
3. /data/riotbuild can not be written to if not overmounted using "docker run -v". There are use-cases where this causes trouble.
> misc improvements

- Dockerfile
This adds libsocketCAN support, needed for https://github.com/RIOT-OS/RIOT/pull/5793
> dockerfile: add libsocketCAN

- Dockerfile
Python3 crypto libraries are needed for Murdock to generate standard crypto keys in order to sign valid images.
For now this is only used for MCUBoot support.
> Dockerfile: add python3 crypto libraries

- Dockerfile
needed by https://github.com/RIOT-OS/RIOT/pull/7794 in order to create a C header file containing the data of arbitrary files as char array.
> add vim-common, which provides /usr/bin/xxd

- Dockerfile
This adds the pep8 command dependency as required for https://github.com/RIOT-OS/RIOT/pull/8036.
> add pep8 dependency

- Dockerfile
Required for https://github.com/RIOT-OS/RIOT/pull/8078
> add flake8 dependency

- Dockerfile
In https://github.com/RIOT-OS/RIOT/pull/7437 we figured that our docker image is shipping a rather old CMake version. CCN-lite requires CMake >= 3.7.
> cmake: install version 3.10

- .travis.yml
Not sure if it's worth it but I think it would be great to have some kind of build check of the Docker image when one introduces new packages, etc
This PR just add a travis configuration file that just triggers a new build of the Docker image. If accepted, we'll have to setup the travis integration.
~We could even publish new images automatically on successful builds (only from master branch of course).~
> add travis automatic build on PRs

- Dockerfile
This PR adds `automake` to the RIOT docker image. It's (at least) required for building OpenThread.
> dependencies: add automake

- Dockerfile
I have added build commands for ESP8266 toolchain as required for my EPS8266 port of RIOT, see PR [#8921](https://github.com/RIOT-OS/RIOT/pull/8921).
The toolchain is located in ```/opt/esp``` after installation and requires approximately 140 MB. Path variables in make point to this directory per default. 
I guess, adding ESP8266 toolchain to riotdocker is also a prerequisite for murdock test. Am I right?
> toolchain for ESP8266

- Dockerfile
Not used anymore in RIOT development after https://github.com/RIOT-OS/RIOT/pull/8042 was merged.
~Blocked by #46~
> Drop qemu-system-x86

- Dockerfile
This PR adds `libtool` and `m4`, required for building OpenThread.
I tried to build OpenThread with and without this PR, and this fixes the issue.
~It was rebased into #47~
Since #50 got merged, this should work now!
> Dockerfile: add missing Openthread dependencies

- Dockerfile
This saves around ~~70-80 MB~~ 130 MB in the finished image.
These toolchain binaries are hard links to the same file when installed from source. I think there was some mistake when the tar archives were made that failed to preserve the hard links and instead stores them as separate files. The toolchain tar archive for Cortex-M from ARM _does_ preserve the hard link property, so this file duplication has to be a mistake in the packaging for the RISC-V and MIPS toolchains.
Verified locally that these duplicate files have the same sha1 signature.
> Deduplicate binaries and remove toolchain documentation

- .travis.yml
Print image build size after building it.
This should help debug build size increase.
Check travis output to see if it prints it correctly.
> travis: print build size

- Dockerfile
The purpose of this change is to make the build more explicit with regards to toolchain versions, and to make the ARM installation more similar to the other supported platforms in the container. This will also make transitioning to a newer OS release (#42) easier.
The MD5 sum is verified after download against the expected MD5 sum from the ARM website, this way the user can be certain that this image uses a particular version of the toolchain.
The selected toolchain is the latest release currently available from arm.com, and the same release as found in the PPA. I did not verify that the files are the same in the downloaded archive as in the PPA, but they carry the same GCC version number, so the impact should be minimal.
> ARM: Use ARM provided toolchain archive instead of PPA

- Dockerfile
I have added the installation of the ESP32 toolchain as required for the ESP32 port of RIOT,  PR https://github.com/RIOT-OS/RIOT/pull/9426.
The toolchain is installed in ```/opt/esp``` and requires about 181 MB after cleanup. All path variables in the makefiles of the ESP32 port point to this directory.
> toolchain for ESP32 added

- Dockerfile
Added a comment on where to find toolchain updates for MIPS. It is not obvious where to go when googling for a MIPS toolchain when you don't know where to look.
References RIOT-OS/RIOT#8755
> mips: Add URL for toolchain updates

- Dockerfile
fixes #60 by updating the link to the flex library.
I'm wondering why flex is required this way (the comment says it's a hack but doesn't say why).
> Dockerfile: fix link to flex library

- Dockerfile
From the xsltproc website:
> xsltproc is a command line tool for applying XSLT stylesheets to XML documents. It is part of libxslt, the XSLT C library for GNOME. While it was developed as part of the GNOME project, it can operate independently of the GNOME desktop.
This is necessary e.g. for https://github.com/RIOT-OS/RIOT/pull/7903 and possibly other packages in the future.
> Add xsltproc to build container

- Dockerfile
Add `--no-install-recommends` to apt-get commands to avoid pulling in optional dependencies which are not used by the build process. 
The image size reduction is approximately 430 MB
```
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
riot/riotbuild             norecommends        402547be3514        3 minutes ago       3.34 GB
riot/riotbuild             master              e4c568fc283a        44 minutes ago      3.77 GB
```
This needs a full buildtest run on the new image to ensure that no critical components are missing after adding this flag, but my laptop does not have the disk space or time to do it.
> apt: Use --no-install-recommends to avoid unnecessary extras 

- Dockerfile
This updates to Ubuntu Bionic, which is the most current LTS release.
The ```team-gcc-arm-embedded``` PPA is removed, as it does not support Bionic. The package ```gcc-arm-embedded``` was from that PPA, but there is an equivalent ```gcc-arm-none-eabi``` that is probably newer anyway.
I tested with ```docker build -f Dockerfile ./``` and it builds successfully.
Required for: https://github.com/RIOT-OS/RIOT/issues/9405
> Update to Ubuntu Bionic

- Dockerfile
The current way of first recursively cloneing the esp-idf-repo, then setting the wanted commit, doesn't work. Some of the submodules have advanced too far. The result is that building the current Dockerfile fails.
This PR fixes this by first cloning un-recursively, setting the wanted commit, then clone the submodules from a known state.
> esp32: fix toolchain download

- .travis.yml
This PR tries to add a build of hello-world for all installed toolchains.
The idea is to get a basic notion of whether the container is able to build RIOT.
I have randomly selected one board for each installed toolchain.
> travis: add riot testbuild

- Dockerfile
This somewhat ensures a consistent utf-8 configuration.
Without any LANG or LC_ALL setting, Linux systems default to the C locale. This breaks many utf8 applications. Most notably, python is much more sane when running in utf8 locales.
(See #73 , https://github.com/RIOT-OS/RIOT/issues/11691)
> add ENV LC_ALL|LANG=C.UTF-8

- Dockerfile
In https://github.com/RIOT-OS/RIOT/pull/10801#pullrequestreview-194277653 I made a promise to remember that we check if `memset()` still isn't optimized out for sensitive data. This comment hopefully helps us to keep that promise.
> esp32: add reminder to memset() problem

- Dockerfile
This adds [Vera++](https://bitbucket.org/verateam/vera/wiki/Introduction) to the installation. The CI script to run the check can be found in RIOT-OS/RIOT#9778.
> Dockerfile: add vera++

- Dockerfile
The current risc-v toolchain makes some applications not pass the tests.
This gcc 8.1 based one works fine. I didn't dig for reasons. My gut feeling is that the newly available newlib-nano saves enough stack space to not break the tests.
Supercedes #62.
~~Waiting for #70.~~
> update riscv toolchain to 8.2

- requirements.txt
This PR adds needed dependencies for SUIT (https://github.com/RIOT-OS/RIOT/pull/11818)
To test, make sure docker is correctly installed.
Then:
- check out this PR
- build the container (eg. ```docker build -t riotdocker_dev .```)
- check out #11818
- from the checkout root, run ```riot (suit-pr)]$ docker run -ti --rm -v $(pwd):/data/riotbuild -u $(id -u) riotdocker_dev /bin/bash```
- in the container, ```cd examples/suit_update; make suit/publish```
It should succeed.
Otherwise this shouldn't affect anything, as this is only an addition of python packages.
> add python dependencies for SUIT

- requirements.txt
I use `scapy` generally for network tests. Version 2.4.3 includes the MQTT-SN support [I provided to the scapy project](https://github.com/secdev/scapy/pull/2131) which is required for https://github.com/RIOT-OS/RIOT/pull/11823 (and a soon-to-be-provided `asymcute` version of that test).
> Add scapy as requirement

- Dockerfile
- install_requirements.txt
- requirements.txt
Should fix https://github.com/RIOT-OS/RIOT/issues/12058 when deployed on the workers. I'm also wondering if the `install_requirements.txt` file is really needed.
> python: keep setuptools during installation of python packages

- Dockerfile
This PR follows https://github.com/RIOT-OS/riotdocker/pull/79#issuecomment-523888269 from @jcarrano which makes good sense to me.
Since Python package requirements are evolving quite often, this will avoid docker to rebuild layer (like ESP32 toolchain) coming after Python packages installation in the Dockerfile.
> Dockerfile: move Python requirements installation at the end

- Dockerfile
When using the nanopb package, a version of protoc is needed to generate .c and header files from the protobuf definitions.
This adds protoc to riotdocker.
Needed for https://github.com/RIOT-OS/RIOT/pull/11565
> Dockerfile: install protobuf-compiler via apt package manager

- .travis.yml
- change to use release branch instead of tag
- remove obsolete 2019.04 hack
- also bump travis container to use the bionic image (was using trusty from 14.04)
> travis: bump travis to bionic, RIOT release to 2019.07-branch

- Dockerfile
This PR adds the codespell dependency to the container: it is required for https://github.com/RIOT-OS/RIOT/pull/12232
> Dockerfile: add codespell dependency

- Dockerfile
This upgrades the MIPS toolchain to the latest version.
Supercedes #47.
> update MIPS toolchain version

- Dockerfile
Reference
https://docs.docker.com/engine/reference/builder/#maintainer-deprecated
> [Docker] replace deprecated MAINTAINER with LABEL

- Dockerfile
- requirements.txt
Unfortunately the version of codespell installed by apt doesn't contain some of the options used in https://github.com/RIOT-OS/RIOT/pull/12232
This PR is installing codespell via pip3 with the latest current version (1.16) to be sure all required features can be used.
> codespell: install via pip instead of apt

- Dockerfile
When building the container locally, it failed with missing `ffi.h` include while installing the python requirements:
```
building '_cffi_backend' extension                                                                                             
creating build/temp.linux-x86_64-3.6                                                                                           
creating build/temp.linux-x86_64-3.6/c                                                                                         
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdat$
-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/pyth$
n3.6m -c c/_cffi_backend.c -o …
```
> add libffi_dev (needed by python cffi)

- Dockerfile
This PR adds the current official TI msp430 ELF toolchain.
@gschorcht @geromueller please take a look!
Compared to #82 , it avoids building the toolchain from source.
Compared to #62, this is using TI's current release, and does not install the support files.
PR to RIOT master updating msp430: RIOT-OS/RIOT#12457, which includes just the used msp430-support-files.
This PR will not do any compilation test on travis, as there's no code supporting this in master...
> add TI msp430 gcc 8.3.0 ELF/newlib toolchain

- Dockerfile
This PR adds a new ESP8266 toolchain that uses a newer GCC version and the new ESP8266 RTOS SDK instead of the old ESP8266 NONOS SDK. It is required for the reimplementation of the ESP8266 RIOT port in PR https://github.com/RIOT-OS/RIOT/pull/11108.
This new toolchain is installed in parallel to the old one to be able to compile the current master but also to compile the PR  https://github.com/RIOT-OS/RIOT/pull/11108. Once PR https://github.com/RIOT-OS/RIOT/pull/11108 is merged, the old toolchain can be removed.
The additional environment variable settings for the old toolchain are required to be able to divide the toolchain in RIOT's build system.
> esp8266: toolchain update for the new RTOS SDK

- Dockerfile
This PR changes the reference to another commit of the [precompiled ESP32 toolchain repository](https://github.com/gschorcht/xtensa-esp32-elf) to update the toolchain to a version that is required to fix issue https://github.com/RIOT-OS/RIOT/issues/13133.
Compilation of all examples/tests in current RIOT master should succeed.
Requires PR https://github.com/RIOT-OS/RIOT/pull/13141
> esp32: update for toolchain version v2

- Dockerfile
This PR switches the (currently not used because it is broken) TI msp430-elf toolchain with the newly created one from https://github.com/RIOT-OS/toolchains/releases.
This currently won't be tested by travis as there's no corresponding code in master.
I tested building with https://github.com/RIOT-OS/RIOT/pull/12457, works fine.
Updates / fixes #91.
> msp430-elf: switch to RIOT-OS/toolchains 9.2.0-9

- Dockerfile
This PR just references another commit [c0174ef](https://github.com/gschorcht/RIOT-Xtensa-ESP8266-RTOS-SDK/commit/c0174eff7278eb5beea66ce1f65b7af57432d2a9) of the ESP8266 toolchain repository which simply contains a number of function call replacements in SDK libraries.
In order to be able to control the log output from ESP8266 SDK libraries according to the defined log level, a number of library-specific `printf` functions were implemented in RIOT with PR [#12998](https://github.com/RIOT-OS/RIOT/pull/12998) for use by the SDK. These library-specific `printf` functions intercept the log output of the SDK and redirect it to the RIOT log macros.
To get these SDK library-specific functions working, all `printf`/`ets_printf` calls in SDK libraries have to be replaced by the calls of the …
> esp8266: replacement of SDK library printf functions

- Dockerfile
This mostly brings arm gcc to gcc 8.
The PR also somewhat parameterizes the URL so future updates will be a little easier.
> bump ARM toolchain to 9-2019-q4

- Dockerfile
This PR updates the ESP32 toolchain to a `newlib` version with `nano-malloc` and `nano-formatted-io`. The toolchain update is required to support multiple heaps.
The toolchain update has no impact on existing RIOT code, but is a prerequisite for PR https://github.com/RIOT-OS/RIOT/pull/13517.
> esp32: newlib with nano-malloc and nano-formatted-io

- .travis.yml
#104 stumbled over a long fixed compilation issue because travis is still testing against 2019.07.
This PR updates the branch travis compiles against to 2020.04.
> bump travis RIOT version to 2020.04-branch

- Dockerfile
This PR adds the afl toolchain to the dockdr image. It is required for building _fuzzing_ applications in RIOT.
Note that the afl toolchain is not tested on Murdock, see [here](https://github.com/RIOT-OS/RIOT/blob/379d113af79e57c4d0c1dad134014a507d779cbb/.murdock#L139-L140), but it is required when using `compile_and_test_for_board.py`:
For example, in RIOT:
```
BUILD_IN_DOCKER=1 ./dist/tools/compile_and_test_for_board/compile_and_test_for_board.py . native --applications="fuzzing/*"
```
fails with the current Docker image because the afl toolchain is missing in the image.
<details><summary>with this PR:</summary>
```
BUILD_IN_DOCKER=1 ./dist/tools/compile_and_test_for_board/compile_and_test_for_board.py . native --applications="fuzzing/*"
INFO:native:Saving toolchain …
```
> Dockerfile: install afl++ apt package

- requirements.txt
`dist/tools/suit/suit-manifest-generator/suit_tool/create.py` requires cbor2 as of https://github.com/RIOT-OS/RIOT/pull/14436.
Install it to being able to build the SUIT update going forward.
> requirements.txt: add cbor2

- requirements.txt
It will be required by https://github.com/RIOT-OS/RIOT/pull/14595 and it's not available in the Docker image.
> requirements.txt: add dependency to jinja2 template engine

- Dockerfile
Since the official RIOT release 2020.01 now uses the new ESP8266 implementation with the new toolchain based on the ESP8266 RTOS SDK, we can remove the old toolchain.
> esp8266: remove the old toolchain

- requirements.txt
This adds [`riotctrl`](https://github.com/RIOT-OS/riotctrl/) to the docker image.
> requirements.txt: add riotctrl as a dependency

- Dockerfile
- cross-riscv-none-embed.txt
Add support for picolibc in the docker image.
This builds the picolibc implementation for arm, esp32 and riscv32. The riscv implementation seems to work with RIOT-os/RIOT#12305, but I haven't tested it yet on actual hardware as I don't own one of the hifive boards.
Meson is grabbed from pip and not from the bionic repos because the version in bionic is too old (0.45 vs 0.50)
An alternative approach would be to simply grab the debian buster deb's and install those. Please let me know what is preferred here.
> picolibc: Add initial support for picolibc

- Dockerfile
- hooks/build
Currently, there's no way to get the git commit of the running docker container from within the container.
This PR uses Docker hub magic (namely, a custom build hook) to get the output of "git describe" into the container image.
See https://github.com/docker/hub-feedback/issues/600 for others having similar issue and solution.
> create /etc/riotbuild_version with "git describe --always" output

- requirements.txt
The upstream suit-manifest-generator [requires](https://github.com/ARMmbed/suit-manifest-generator/blob/master/setup.py#L55) the pyhsslms package.
In order to use the upstream version as a package, also include this in riotdocker.
Needed for https://github.com/RIOT-OS/RIOT/pull/15095
> requirements.txt: add pyhsslms

- requirements.txt
The suit-manifest-generator script uses the [colorama](https://github.com/ARMmbed/suit-manifest-generator/blob/master/setup.py#L57) package.
In order to swich to the upstream version, also include it in our requirements.txt.
Needed for https://github.com/RIOT-OS/RIOT/pull/15095
> requirements.txt: add colorama

- .travis.yml
This PR adds running of the static tests to .travis.
Unfortunately RIOT's static tests pretty much assume to be run with changed files versus master, so this won't check *all* files, but *none*, if a reference branch is used by the specific test. All checks using "changed_files()" are affected.
But, babysteps...
> travis: run static tests

- requirements.txt
This PR bumps the code spell version used in the docker image, new version is smarter regarding false positive detection.
> requirements.txt: bump codespell version

- requirements.txt
This PR bumps the flake8 version used in the docker image, new version is less permissive with lint issues.
> requirements.txt: bump flake8 to 3.8.4

- Dockerfile
In https://github.com/RIOT-OS/RIOT/pull/15667 I noticed that `uncrustify` is not run in the static tests, since it isn't installed into our Docker. Here is the fix for that.
> Dockerfile: add uncrustify

- riotbuild/requirements.txt
The optional `rapidjson` dependency was added to `riotctrl` in https://github.com/RIOT-OS/riotctrl/pull/8 for a more lax parsing of JSON objects such as trailing commas within an object like this:
```json
{
"one": 1,
"two": 2,
"three": {"I": "have", "more": "members",},
}
```
This adds that optional dependency. However, [dependency resolution was broken in `v0.2.0` and `v0.2.1`](https://github.com/RIOT-OS/riotctrl/pull/14), we need to use at least `v0.2.2`.
> riotbuild: include rapidjson extras for riotctrl

- riotbuild/Dockerfile
This PR updates the version of the riscv toolchain to 10.1.0. The prebuilt toolchain comes from [this repository](https://github.com/xpack-dev-tools/riscv-none-embed-gcc-xpack) which is the one recommended one on https://github.com/gnu-mcu-eclipse/riscv-none-gcc (this one is deprecated).
This PR is required for https://github.com/RIOT-OS/RIOT/pull/15958
> riotbuild: bump riscv toolchain version to 10.1.0

- .travis.yml
This bumps the RIOT release version used in Travis. This is required by #107
> .travis.yml: bump RIOT version

- riotbuild/Dockerfile
Bump MIPS toolchain version to 2020.06-01 (gcc 9.3.0).
This breaks the build on the current RIOT version so we need to fix them on RIOT first.
> Dockerfile: bump MIPS toolchain to 2020.06-01 (gcc 9.3.0)

- riotbuild/requirements.txt
I don't know how the riot container even can build (probably because the dependency fix was introduced after v0.2.2 of `riotctrl`), but `riotctrl` requires at least `pexpect` 4.7. So this bumps both `pexpect` and `riotctrl` to the most current version.
> riotbuild: bump version of pexpect and riotctrl

- .travis.yml
- bors.toml
This adds a minimal [bors](https://github.com/bors-ng/bors-ng) configuration.
> Do we want this one?
Pros:
- no two PR can pass CI individually and then cause an error when merged ("
- no need to rebase ACKed PRs, bors merges into master before testing
- if multiple PR are ACKed at the same time, bors builds them together
Cons:
- new tool (for us at least)
- PR's actually show as closed even though bors merges their content, as bors merges it's staging branch
> CI: add bors configuration

- .travis.yml
This PR makes travis log into docker hub.
This is only done when building the bors branches (master, trying, staging), as for travis PR branch builds, travis doesn't supply the necessary environment variables.
> travis: log into docker hub when building bors branches

- .github/workflows/build.yml
- riotbuild/Dockerfile
- static-test-tools/Dockerfile
This PR is a simplified alternative to https://github.com/RIOT-OS/riotdocker/pull/136, the major difference comes from it using the `docker` driver instead of `docker-container` driver for buildx which basically makes it behave like regular docker, so: no-cache, no multiplatform build, but the workflow can be simplified a lot.
I personally think we lose a lot with this, but being able to replace Travis, Docker with only GitHub actions, integrate versioning is a huge plus and this PR should be easier to integrate and to understand (there are a lot of workarounds to be done with `docker-container` driver as seen in #136).
> .github: add workflow to build and test images, using `docker` driver

- .github/workflows/build.yml
Master build failed because the wrong registry was used since it was hardocded. https://github.com/RIOT-OS/riotdocker/actions/runs/903174401
> .github/workflows/build.yml: fix DOCKER_REGISTRY arg

- .github/workflows/build.yml
Another issue that snuck in during the renaming... sorry for all the wasted ci time.
> .github/workflows/build.yml: fix wrong secrets reference

- .github/workflows/build.yml
I initially misunderstood how our branches were named, and though I could re-user the RIOT_BRANCH use for testing as the tag for the image, but IMO it makes more sense to tag the next release version. Instead, so how I see it would be:
- tag the DOCKER image with the next release version (so in current case `2021.07`) while building against `2021.04-branch`
- once release is over switch RIOT_BRANCH to `2021.07-branch` and `VERSION_TAG` to `2021.10`
Maybe it's a good time to discuss how to version our images as well.
> .github/workflows/build.yml: bump RIOT branch

- .github/workflows/build.yml
- c2rust-built/Dockerfile
- c2rust-built/README.md
- riotbuild/Dockerfile
The c2rust program (required in addition to Rust itself) is installed
for what is for most intents and purposes a third party container, but
happens to have its sources shipped along the other containers.
---
This is a minimal version competing with #141 -- we can still get c2rust to fully integrate over time, but right now there's a third party (happens to be me) who publishes a suitable base container, which is not much more or less transparently managed than any other base container (especially immunant/c2rust which it itself is based on), and hey by the way even the Dockerfile for that container is shipped here (but more for informational purposes, not because CI would access it).
> riotbuild: Install Rust (minimal edition)

- static-test-tools/Dockerfile
Alternative to https://github.com/RIOT-OS/riotdocker/pull/139.
kaspar030/uncrustify-builder now builds and publishes a container with recent uncrustify binary, which can simply be copied from there.
This upgrades riot/riotbuild's Uncrustify to versoin 0.73.0!
> static-test-tools: use uncrustify from kaspar030/uncrustify-builder

- .gitattributes
- .github/workflows/build.yml
- riotbuild/Dockerfile
- riotbuild/files/libsocketcan-dev_0.0.11-1_i386.deb
- riotbuild/files/libsocketcan2_0.0.11-1_i386.deb
- riotdocker-base/Dockerfile
- static-test-tools/Dockerfile
- static-test-tools/files/coccinelle_1.0.8~19.04npalix1_amd64.deb
This PR updates the base for our build container to Ubuntu focal (2020.04).
There's no coccinelle package anymore for focal in the coccinelle ppa, so I've added a binary package.
Same with libsocketcan.
In order to not clutter the git history with binary data, those package files have been added using git lfs, and the build.yml workflow has been adapted to pull the lfs files.
~~WIP, want to see travis output~~
> Update to Ubuntu 2020.04 LTS

- riotbuild/requirements.txt
This replaces the [unmaintained `pycrypto`](https://github.com/pycrypto/pycrypto/issues/173) (which has several vulnerabilities, see https://github.com/RIOT-OS/RIOT/pull/17107) with the more up-to-date [`pycryptodome`](https://pypi.org/project/pycryptodome/).
> riotbuild: use pycryptodome instead of pycrypto

- riotbuild/Dockerfile
* Add what is needed to experiment with AVR (not fully supported for Rust-on-RIOT, but way easier to test being in the docker build as I haven't had AVR toolchains installed around for a long time, though they probably still can be installed easily)
* Update Rust nightly (that's a semi-regular thing since we decided to pin the version in https://github.com/RIOT-OS/riotdocker/pull/141#issuecomment-909035011 which also went into #152)
> Rust updates

- c2rust-built/Dockerfile
- c2rust-built/README.md
- c2rust-built/debian/control
- c2rust-built/debian/rules
- riotbuild/Dockerfile
This issue tracks changes needed in the Rust installation (OK: C2Rust -- the rest should just work) when #104 is rebased and gets merged.
By building c2rust on the same Ubuntu release (focal), the friction between different installed LLVM versions will be reduced.
This
* switches from using c2rust's shipped build containers (which made sense back when supported Ubuntus had those old LLVM versions) to a plain feisty base,
* consequently installs the build-deps manually, and
* builds a Debian binary package in the course of installing c2rust.
The latter is done to get us rid of the manual `apt-get install llvm-7-dev` (and pray that it matches what c2rust needs) in favor of copying the .deb out of the c2rust image and getting the right build-deps automatically. (A part of building a Debian …
> Build C2Rust on focal

- murdock-worker/Dockerfile
The latest redis-py pulled through dwq spews out a [warning](https://github.com/redis/redis-py/blob/4e9cc015e32ef305429ff9dfa200e28dd63e6663/redis/connection.py#L71) if hiredis is not installed.
Somewhere down the line, that gets turned into a job, and produces murdock output like:
> **Failed jobs**: [UserWarning:/redis-py/works/best/with/hiredis./Please/consider/installing](https://ci.riot-os.org/RIOT-OS/RIOT/17221/b2f9e2c226e7c26abaf22228b2aa396fb85df6e3/output/UserWarning:/redis-py/works/best/with/hiredis./Please/consider/installing.txt)
This is a hotfix that makes the warning go away; where the warning (that should go to stderr and not into jobs) took the wrong turn is yet to be explored.
Build the murdock container and run:
```
$ python3 -c 'import dwq'
```
If all is well, that …
> murdock: Install hiredis

- riotbuild/Dockerfile
This drops a workaround that was necessary during evaluation of #153 in
favor of a more long-term usable distinction between experimentation and
stable delivery, which is necessary until #141 is done properly and
c2rust is built in one go with the rest of this.
---
Cleanup change with no expected actual impact. (Tags diverge because `latest` = `for-riot` was rebuilt after #153 was merged, but any differences should be just because building is not byte-by-byte reproducible.)
> riotbuild: Drop :focal tag in favor of a more stable one

- riotbuild/Dockerfile
This is not aimed for in https://github.com/RIOT-OS/RIOT/pull/16274, but progressively opening up to more architectures, build servers will need this.
> rust: Add support for Cortex-M23, M33 and M33F

- murdock-worker/Dockerfile
bump git-cache version.
provides much faster tag handling.
> murdock-worker: bump git-cache

- murdock-worker/Dockerfile
Reverts RIOT-OS/riotdocker#165
Something is off, I suspect this change. :(
> Revert "murdock-worker: bump git-cache"

- murdock-worker/Dockerfile
bump the dwq tool to ~~0.0.47~~ 0.0.49.
This does not affect riotdocker, only the murdock-worker.
dwq version 0.0.47 has some features that make deploying it with docker-compose a bit easier (mostly, not hard-coding "localhost:7711" for it's disque url).
dwq 0.0.49 brings some bug fixes to dwqw. There's also better reporting (now the checkout time and output is logged in result.json).
> murdock-worker: bump dwq

- .github/workflows/build.yml
- riotbuild/Dockerfile
This PR adds QEMU with it's full-system ARM emulator.
At least the microbit board can be emulated to a large degree with this.
A second commit adds a basic test run of `tests/fmt_print` for microbit, using qemu.
> riotbuild: add qemu-system-arm

- .github/workflows/build.yml
- riotbuild/Dockerfile
With this version it will be possible to use cstr_core >= 0.2.5 (which
future versions of riot-wrappers will depend on)
Testing procedure: Things still build.
> Update Rust nightly version

- murdock-worker/Dockerfile
bumping dwq again.
0.0.51 has a small change, increasing the safety margin the worker uses to time-out jobs itself. This is to prevent a job from being timed-out by disque server, at which point it's output would be lost.
> murdock-worker: bump dwq to 0.0.51

- murdock-worker/Dockerfile
Bump dwq,
upstream contains this commit (apart from the version bump):
https://github.com/kaspar030/dwq/commit/05ae117526d7dbcbac381d53bd9e20d1af8cbc0e
> murdock-worker: bump dwq to 0.0.52

- riotbuild/Dockerfile
The minor fixes correspond to this warning raised by Docker: `apt does not have a stable CLI interface. Use with caution in scripts.`. So use apt-get instead which is consistent with the rest of the commands.
There's a small name duplication removed with coccinelle package using an ARG.
> riotbuild: bump riscv toolchain to 10.2

- .github/workflows/build.yml
This should ensure the installed nanopb package works correctly.
Once merged, https://github.com/RIOT-OS/riotdocker/pull/181 can probably be merged safely.
> CI: add pkg_nanopb test

- c2rust-built/Dockerfile
- c2rust-built/README.md
- c2rust-built/debian/changelog
- c2rust-built/debian/control
- c2rust-built/debian/install
- c2rust-built/debian/rules
C2Rust has accepted most of the patches in the current for-riot; what's left needs riot-sys fixes anyway on the long run.
A sibling PR on RIOT docs is https://github.com/RIOT-OS/RIOT/pull/17536
This is on hold as a draft because it still depends on two things:
-- and then maybe some time for good measure as to not cause any trouble for people on branches that haven't received the no-llvm-asm riot-wrappers update from RIOT yet.
[edit: Turned into a checklist, as first item is done]
> C2Rust: Use upstream as patches are not required any more

- .github/workflows/build.yml
- riotbuild/Dockerfile
This ensures that after the 2020.04 release the supported stable version
can be bumped to Rust 1.61. Using Rust 1.61 to its full potential will
require removing feature declarations, and if riot-wrappers has those
features removed, building it needs a recent nightly (like this) that
does not need them declared.
In addition, it removes a workaround that was needed before the 2022.01 release for the build tests; they are now performed on whatever RIOT branch is selected (IIUC the last release -- anyhow, like all the other build tests).
---
In terms of testing, this should be covered well by the test; in addition, local build tests are being done against the latest RIOT master, and with a larger example than the hello-world.
> rust: Update nightly version

- riotbuild/Dockerfile
With builds of RIOT on stable Rust becoming more and more attainable (basics are in, 1.60 is adding builds on native without undue complexity, 1.61 will add support for shell and SAUL), at some point we should make that part of the test suite.
The present commit is a first step there. It adds "beta", but the [plan](https://forum.riot-os.org/t/release-2022-04-dates-and-feature-requests/3548/3) is to switch that over to 'stable' when 1.60 becomes stable.
This likely doubles the size of the installed Rust (rustup itself is common but rather small; compiler, core libraries and source code will be duplicated); the build tests that give me numbers are still running. Possibly, the source code can be left out of the beta image -- that's mainly needed when rebuilding the core libraries to the …
> rust: Add beta version

- riotbuild/Dockerfile
As reported in issue #184, the installation of `emlearn` seems to fail in because of missing `pybind11` module, but is actually successful. The reason is that the wheels for `ed25519`, `cbor`, `scapy`, `emlearn` and `riotctrl` are built before the other collected packages are installed.
The extensive error output on the first failed iteration of the `emlearn` installation is very confusing and can be prevented by explicitly installing the `pybind` package before installing the other required packages, as suggested in this PR.
> riotbuild: avoid errors when emlearn is installed

- riotbuild/Dockerfile
Switching over as planned[1] for the pending release.
[1]: https://forum.riot-os.org/t/release-2022-04-dates-and-feature-requests/3548/3
> rust: 1.60 has been released

- riotdocker-base/Dockerfile
Workaround for https://github.com/actions/checkout/issues/760 (caused by a [git vulnerability](https://github.blog/2022-04-12-git-security-vulnerability-announced/)).
> CI: add git safe directory

- .github/workflows/build.yml
Disables "make buildtest" output redirection, so build errors don't get lost.
> CI: do verbose "make buildtest"

- riotbuild/Dockerfile
Reverts RIOT-OS/riotdocker#190
https://github.com/RIOT-OS/riotdocker/pull/190#issuecomment-1125785423
> Revert "Dockerfile: replace ESP32 toolchain by Espressif's precompiled toolchain gcc 8.4.0"

- c2rust-built/Dockerfile
- c2rust-built/README.md
- c2rust-built/debian/changelog
- c2rust-built/debian/install
- c2rust-built/debian/rules
- riotbuild/Dockerfile
Things got a lot easier since upstream did awesome work leading up to https://github.com/immunant/c2rust/issues/365.
This release allows riot-sys to do away with a quite a few workarounds, and resolves a blocker for https://github.com/RIOT-OS/RIOT/pull/18056 in passing.
This is a prerequisite for https://github.com/RIOT-OS/riotdocker/pull/189 (in the course of which C2Rust can then be simplified further, as we can just use Rust from Ubuntu to build it, or even simply let this become a Debian package over time).
> Update C2Rust to 0.16

- riotbuild/Dockerfile
This PR is the second try to
- replace the ESP32 toolchain with gcc 5.2.0 specifically compiled for RIOT with the precompiled toolchain from Espressif with gcc 8.4.0
- add the toolchain for ESP32C3
The compilation for all applications in `examples` and `tests` was tested for all ESP32 boards.
It requires the merge of PR https://github.com/RIOT-OS/RIOT/pull/18106.
> Dockerfile: replace ESP32 toolchain by Espressif's precompiled toolchain gcc 8.4.0

- riotbuild/Dockerfile
Now that the 2022.07 release branch is created, it is a good time to go the next migration step and to add Espressif's vendor toolchain for ESP32-S3 to be able to compile RIOT-OS/RIOT#18185 in CI. The toolchain has a size of 292 MByte.
> riotbuild: add ESP32-S3 toolchain

- riotbuild/Dockerfile
Add Espressif's vendor toolchain for ESP32-S2 to be able to compile https://github.com/RIOT-OS/RIOT/pull/18235 in CI. The toolchain has a size of 290 MByte
> riotbuild: add ESP32-S2 toolchain

- riotbuild/Dockerfile
- riotdocker-base/Dockerfile
- static-test-tools/Dockerfile
- static-test-tools/files/coccinelle_1.0.8~19.04npalix1_amd64.deb
Trying to just bump. (/me crossing fingers)
> riotdocker-base: bump to 2022.04 (Jammy Jellyfish)

- .github/workflows/build.yml
- riotbuild/Dockerfile
This branch is used for investigating failures encountered after merging #189, in which C2Rust errs internally. Upstream might already have solved it.
This builds on #209.
> C2Rust updates / fixes

- .github/workflows/build.yml
MIPS support was removed: https://github.com/RIOT-OS/RIOT/pull/18562
> remove pic32-wifire from BOARDS

- .github/workflows/build.yml
... to be merged *after* 2022.10 has been released ...
> .github/workflows/build.yml: bump VERSION_TAG to `2023.01`

- riotbuild/Dockerfile
As the title says...
Should fix https://ci.riot-os.org/results/8e1338abe27b407c8d2677e3a42ebb7e/output/builds/examples/riot_and_cpp/nrf52840dk:gnu.txt and similar failures.
> Dockerfile: install libsdc++-arm-none-eabi-*

- .github/workflows/build.yml
This should prevent regressions when building application requiring cpp.
> .github: add step to build a cpp application

- riotbuild/Dockerfile
- riotbuild/cross-riscv-none-embed.txt
It pains me a lot but the bad debian newlib package won't be fixed in time for the hard freeze, and neither will we sort out the issues with picolibc as default, in the week before x-mas. :(
This reverts commit 20529a8aa6996c784e2ca2921e1356ee1fcdd5ee (#116), reversing changes made to 604bc231ffab46426f2dbf7a0d3439ab1f52059c.
> Revert "Merge #116"

- .github/workflows/build.yml
Copy of https://github.com/RIOT-OS/riotdocker/pull/182 that is rebased (actually, the logical removals are re-applied, but it's dressed with the same author and commit message).
> actions: remove obsolete switcharoo

- murdock-worker/.gitattributes
- murdock-worker/Dockerfile
- murdock-worker/files/ccache-4.7.4-linux-x86_64.tar.xz
ccache version 4.7 adds the option to have a remote-only cache on secondary storage (e.g., **redis**).
I have a [branch](https://github.com/RIOT-OS/murdock-worker/pull/5) modifying the murdock worker docker-compose to add a redis instance for caching.
The ccache binary is the official binary release from https://ccache.dev/download.html.
(debians bookworm has a .dpkg, but that's not compatible to our Ubuntu's older libraries).
My hope is that a local redis scales better with larger caches, which have shown to stall builds when the cache is full and needs to be cleaned (@cgundogan remember the sawtoothing?). redis LRU is cheap.
Also, redis handles persistence (compared to tmpfs), which would **make reboots/restarts not loose all of ccache**.
Potentially, redis can be distributed, so e.g., …
> murdock_worker: add newer ccache (4.7.4)

- .github/workflows/build.yml
With 2023.04 out, it's time to bump riotdocker's base branch.
> CI: bump RIOT_BRANCH to 2023.04-branch and VERSION_TAG to 2023.07

- riotbuild/Dockerfile
This PR upgrades ESP32x toolchains to GCC version 12.2. Since ESP-IDF 5.1 requires this compiler version, this PR has to be merged before we can start with RIOT upgrade to ESP-IDF 5.1.
This PR depends on https://github.com/RIOT-OS/RIOT/pull/19450.
> riotbuild: bump esp32x toolchains to gcc version 12.2

- riotbuild/requirements.txt
Newer versions cause build failures because they expect a newer cython than is provided in jammy; they'd show errors like:
```
Error compiling Cython file:
------------------------------------------------------------
...
ctypedef float s                                                                                                                             ctypedef double d                                                                                                                            ctypedef float complex c
ctypedef double complex z
cdef void caxpy(int *n, c *ca, c *cx, int *incx, c *cy, int *incy) noexcept nogil
^
------------------------------------------------------------
/usr/local/lib/python3.10/dist-packages/scipy/linalg/cython_blas.pxd:20:67: Syntax error in C …
```
> Pin down scipy version

- riotbuild/Dockerfile
Closes: https://github.com/RIOT-OS/riotdocker/issues/208
As of Rust 1.65, there is no need for nightly versions of Rust for RIOT any more.
Currently, this will likely (i.e. unless the nightly selection script happens to manage the case of no nightlies by assigning stable instead) not build, and depends on https://github.com/RIOT-OS/RIOT/pull/18839 which switches away from nightlies. (See there for an overview of all lockstepping involved)
> rust: Only install stable toolchain

- .github/workflows/build.yml
public bors has shut down. switch to merge_queues.
This adds another (third!) build run for each change. But it does keep the semantic conflicts out. So, let's get back the ability to merge and (maybe) optimize later.
> ci: enable "build" for merge groups

- murdock-worker/Dockerfile
- riotbuild/Dockerfile
- static-test-tools/Dockerfile
Closes: https://github.com/RIOT-OS/riotdocker/issues/223
It's a fairly trivial change; if docker consistently works in where it takes fully qualified names, it should just work. (I suppose that means that all is fine if CI says go).
<del>We've also had some build failures on master recently; this PR doubles as a way to flush them out without triggering a possibly unexpected image change mid-release.</del> (that was fixed in #234)
> Explicitly name registries to enable building on podman

- murdock-worker/Dockerfile
This bumps dwq to the latest version.
I'm running this on beast right now.
> murdock-worker: bump dwq to 0.0.60

- .github/workflows/build.yml
- riotbuild/Dockerfile
This PR adds the current development version of the laze build system.
While we're not using it currently, having it in the containers makes experimenting with a possible migration much easier.
The binary is copied from an upstream provided docker container, and clocks in at slightly below 6mb.
> riotbuild: add laze 0.1.20

- murdock-worker/Dockerfile
This PR adds support for the Rust rewrite of `git-cache`.
Please see https://github.com/RIOT-OS/RIOT/pull/20311 for more info..
> murdock-worker: get git-cache-rs, bump dwq to version that supports it

- .github/workflows/build.yml
This should fix #242 b/c 2024.01-branch includes https://github.com/RIOT-OS/rust-riot-sys/pull/36.
> ci: bump RIOT_BRANCH to `2024.01-branch`

- static-test-tools/requirements.txt
This should allow parsing YAML files from Python as part of `static-tests` in the CI.
> static-test-tools: add PyYAML to requirements.txt

- riotbuild/Dockerfile
- riotbuild/cross-riscv-none-elf.txt
Citing https://github.com/xpack-dev-tools/riscv-none-embed-gcc-xpack:
> DEPRECATED! Replaced by xpack-dev-tools/riscv-none-elf-gcc-xpack
So let's do that.
Note: Depends on and includes:
> riotbuild: update RISC-V Toolchain 

- murdock-worker/Dockerfile
When the initial `git cache clone` would have a commit specified (`--commit HASH`), and would trigger the initial clone into the cache directory, the final "checkout HASH" was skipped.
This caused the first dwq worker thread to checkout a branch to fail every job with `./.murdock: not found`.
https://github.com/kaspar030/git-cache-rs/compare/0.1.3...0.1.5
> murdock-worker: bump git-cache-rs to 0.1.5

- riotbuild/Dockerfile
We don't have a user for it yet in RIOT, but I'm working on a tool in https://github.com/RIOT-OS/RIOT/pull/20395 that'd make good use of it. (Essentially it's installing requirements.txt of local tools into venvs on demand, removing the need to have all modules used anywhere as dependencies of RIOT-as-a-whole. It'd still be preferable if the modules were avaialble in riotdocker, but the flexibility makes PRs easier without going through riotdocker first for every single thing.)
Note that you *can* do `python3 -m venv` in the container already, but without the python3-venv Debian package, it can't set up a pip inside venv, and usually that's the very reason why one would use a venv in the first place (and the tool mentioned above relies on it).
> riotbuild: Install python3-venv

- .github/workflows/build.yml
This reverts commit 96287a87b6118d0662bd5a822820d98a8af1261d from [249] that had been required to resolve a deadlock.
[249]: https://github.com/RIOT-OS/riotdocker/pull/249
---
Casually looking at the finished Rust update action I found that the "temporary" #249 has been around for over a month now. I don't remember what the deadlock was with, and none of us left a note, I presume it was something with #249 -- but at any rate, should be resolved now (and build will confirm that).
> Revert "ci: temporarily disable "Rust build test""

- riotbuild/requirements.txt
Bump versions of emlearn, joblib and most important scikit-learn so that https://github.com/RIOT-OS/RIOT/pull/20347 should pass the CI
> riotbuild/requirements: bump emlearn and related dependencies versions

- riotbuild/Dockerfile
Adds the 64-bit version of libsdl2-dev required for the 64-bit version of native.
Needed in RIOT-OS/RIOT#20335
libsdl2-dev has quite a few dependencies and **adds about 190MB to the image**.
If this is too much, I could also blacklist `tests_lvgl` and `tests_lvgl_touch` for the CI.
> riotbuild: add libsdl2-dev:amd64

- riotbuild/Dockerfile
- static-test-tools/Dockerfile
This is the second attempt to fix https://github.com/RIOT-OS/RIOT/pull/20886 by adding Rust earlier in the process, after https://github.com/RIOT-OS/riotdocker/pull/253 taught me that riotbuild is built from static-test-tools.
> Move minimal Rust from riotbuild to static-test-tools

- .github/workflows/build.yml
Regular update like https://github.com/RIOT-OS/riotdocker/pull/236 -- with this, we can start building containers that don't claim to be building for the older versions any more, which is one step in preparing for future releases (eg. where with https://github.com/RIOT-OS/riotdocker/pull/256 there will be changed checkout folders).
> ci: bump RIOT_BRANCH and VERSION_TAG to 2025.01-branch and 2025.04
